[bastion]
nginx ansible_host=13.219.202.209

[load_balancers]
nginx ansible_host=13.219.202.209

[frontend_servers]
frontend ansible_host=10.0.2.171 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=ubuntu@13.219.202.209'

[backend_servers]
backend ansible_host=10.0.2.4 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=ubuntu@13.219.202.209'

[database_servers]
database ansible_host=10.0.2.50 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=ubuntu@13.219.202.209'

[tier_web]
nginx ansible_host=13.219.202.209
frontend ansible_host=10.0.2.171 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=ubuntu@13.219.202.209'

[tier_app]
backend ansible_host=10.0.2.4 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=ubuntu@13.219.202.209'

[tier_data]
database ansible_host=10.0.2.50 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=ubuntu@13.219.202.209'

[region_us_east]
nginx      ansible_host=13.219.202.209
frontend   ansible_host=10.0.2.171 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=ubuntu@13.219.202.209'
backend    ansible_host=10.0.2.4 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=ubuntu@13.219.202.209'
database   ansible_host=10.0.2.50 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=ubuntu@13.219.202.209'

[datacenter_virginia]
nginx      ansible_host=13.219.202.209
frontend   ansible_host=10.0.2.171 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=ubuntu@13.219.202.209'
backend    ansible_host=10.0.2.4 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=ubuntu@13.219.202.209'
database   ansible_host=10.0.2.50 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=ubuntu@13.219.202.209'

[subnet_public]
nginx ansible_host=13.219.202.209

[subnet_private]
frontend   ansible_host=10.0.2.171 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=ubuntu@13.219.202.209'
backend    ansible_host=10.0.2.4 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=ubuntu@13.219.202.209'
database   ansible_host=10.0.2.50 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=ubuntu@13.219.202.209'

[env_production]
nginx      ansible_host=13.219.202.209
frontend   ansible_host=10.0.2.171 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=ubuntu@13.219.202.209'
backend    ansible_host=10.0.2.4 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=ubuntu@13.219.202.209'
database   ansible_host=10.0.2.50 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyJump=ubuntu@13.219.202.209'

[all_nodes:children]
bastion
frontend_servers
backend_servers
database_servers

[all_nodes:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/aws-helpdesk

[database_servers:vars]
mysql_port=3306
mysql_bind_address=10.0.2.50

[backend_servers:vars]
flask_port=5000
flask_env=production

[frontend_servers:vars]
node_env=production
react_port=3000
